### ISSUE TITLE
new branch for only post videos

### ISSUE THREAD

**Issue by bugbounted** [Aditya-Rajgor/Reddit-to-Instagram-automation#1]
Hi Aditya-Rajgor,
please make new branch for only post videos into instagram .
waiting for your commits :)
finest regards

**Comment by Aditya-Rajgor** [comment]
Hi @pmbeman, 
At this point, I don't think making a separate branch necessary. 
However, I have added a new file `WithVideo.py` which supports `images`, `gifs`, and `videos`.

**Comment by bugbounted** [comment]
Hi Aditya-Rajgor,
thanks for your changes on repo but if its possible make one edition of your code for only post videos not with mixed pics posts .
finest regards

**Comment by Aditya-Rajgor** [comment]
Hello, Creating a script for only `video` is not a big deal, I have made changes to the file and created a new one `OnlyVideo.py`. It isn't tested yet, but it should work fine.
