### ISSUE TITLE
can you change video only mode workflow ?

### ISSUE THREAD

**Issue by herokuhint** [Aditya-Rajgor/Reddit-to-Instagram-automation#2]
Hi Aditya ,
please if it's possible make changes to default videos post workflow , at this time , your code read pre scraped link from csv & make post , please make new version that can waiting for new video post on target subreddit & repost it with translated caption using yandex translate api & then post to Instagram.
waiting for your response
finest regards

**Comment by Aditya-Rajgor** [comment]
Hey @herokuhint 
I am quite not clear what you want. 
The script doesn't read posts from the `csv`. The `csv` file is just to make sure that we are not repeating the identical posts again. It checks if the post already exists in the database(csv). 

Regarding the waiting of post, it is certainly possible, you just need to grab the timestamp of the last post and get the difference from the current timestamp. Set the threshold to define the new post, and there you go.

Do let me know from where did you find this repo and any other question related to this issue or repo

**Comment by Aditya-Rajgor** [comment]
...
